name: Deply AWS

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -o '${{ github.woorkspace }}/out'
      
    - name: Zip Package
      run: |
        cd ${{ github.workspace }}/out
        zip -r ${{ github.workspace }}/out.zip *
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v13
      with:
        aws_acess_key: ${{ secrets.AWS_ACCESS_KEY_ID }}        
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: codingchallenge
        environment_name: codingchallenge-env
        Region: us-east-1
        vesion_label: ${{ github.run_id }}
        version_description: ${{ github.sha }}
        deployment_package: ${{ github.workspace }}/out.zip
